const path = require('path')
const BDD = require(path.resolve('Database'))
const lib = require(path.resolve('lib'))

const DB = new BDD()
const token = lib.getNewToken()
console.log(token)
DB.init()
.then(() => DB.addToken(lib.getNewToken()))
.then(() => DB.addToken(lib.getNewToken()))
.then(() => DB.addToken(token))
.then(() => DB.addToken(lib.getNewToken()))
.then(() => DB.addToken(lib.getNewToken()))
.then(() => DB.getToken(token))
.then((row) => {
	console.log(row)
	return Promise.resolve()
})
.then((row) => DB.close())
.catch(err => console.log("[ERROR]", err))
