const path = require('path')
const moment = require('moment')
const Database = require(path.resolve('Database/Database'))
const lib = require(path.resolve('lib'))

const DB = new Database()
const token = lib.getNewToken()
console.log(token)
DB.init()
.then(() => DB.addToken(lib.getNewToken()))
.then(() => DB.addToken(lib.getNewToken()))
.then(() => DB.addToken(token))
.then(() => DB.addToken(lib.getNewToken()))
.then(() => DB.addToken(lib.getNewToken()))
.then(() => DB.getToken(token))
.then((row) => {
	console.log(row)
	return Promise.resolve()
})
.then(() => DB.getTokensSince(lib.momentToDateTime(moment().subtract(30, 'seconds'))))
.then((rows) => {
	console.log(rows)
	return Promise.resolve()
})
.then((row) => DB.close())
.catch(err => console.log("[ERROR]", err))
