const TOKENS_TABLE_NAME = 'tokens'
const COLUMN_TOKENS_ID = 'tokens_id'
const COLUMN_TOKENS_VALUE = 'tokens_value'
const COLUMN_TOKENS_TIMESTAMP = 'tokens_timestamp'


const SQL_CREATE_TABLE = `
CREATE TABLE IF NOT EXISTS ${TOKENS_TABLE_NAME} (
 ${COLUMN_TOKENS_ID} INTEGER PRIMARY KEY AUTOINCREMENT,
 ${COLUMN_TOKENS_VALUE} TEXT NOT NULL UNIQUE NOT NULL,
 ${COLUMN_TOKENS_TIMESTAMP} DATETIME NOT NULL
);
`

const SQL_ADD_TOKEN_PARAM_VALUE = '$tokenValue'
const SQL_ADD_TOKEN_PARAM_TIMESTAMP = '$TimestampValue'
const SQL_ADD_TOKEN = `
INSERT INTO ${TOKENS_TABLE_NAME} (
 ${COLUMN_TOKENS_VALUE},
 ${COLUMN_TOKENS_TIMESTAMP}
)
VALUES (
${SQL_ADD_TOKEN_PARAM_VALUE},
${SQL_ADD_TOKEN_PARAM_TIMESTAMP}
);
`

const SQL_GET_TOKEN_PARAM_VALUE = '$tokenToGet'
const SQL_GET_TOKEN = `
SELECT * FROM ${TOKENS_TABLE_NAME}
WHERE ${COLUMN_TOKENS_VALUE} = ${SQL_GET_TOKEN_PARAM_VALUE}
`

const SQL_GET_TOKEN_SINCE_DATE_PARAM_TIMESTAMP = '$dateParam'
const SQL_GET_TOKEN_SINCE_DATE = `
SELECT * FROM ${TOKENS_TABLE_NAME}
WHERE ${COLUMN_TOKENS_TIMESTAMP} >= ${SQL_GET_TOKEN_SINCE_DATE_PARAM_TIMESTAMP}
`

module.exports = {
	TOKENS_TABLE_NAME,
	COLUMN_TOKENS_ID,
	COLUMN_TOKENS_VALUE,
	COLUMN_TOKENS_TIMESTAMP,

	SQL_CREATE_TABLE,

	SQL_ADD_TOKEN,
	SQL_ADD_TOKEN_PARAM_TIMESTAMP,
	SQL_ADD_TOKEN_PARAM_VALUE,

	SQL_GET_TOKEN,
	SQL_GET_TOKEN_PARAM_VALUE,

	SQL_GET_TOKEN_SINCE_DATE,
	SQL_GET_TOKEN_SINCE_DATE_PARAM_TIMESTAMP
}